# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: students.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='students.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0estudents.proto\"\x8d\x01\n\x07Student\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tstudentId\x18\x02 \x01(\t\x12!\n\x04\x64\x65pt\x18\x03 \x01(\x0e\x32\x13.Student.Department\">\n\nDepartment\x12\x14\n\x10\x43OMPUTER_SCIENCE\x10\x00\x12\x1a\n\x16\x45LECTRICAL_ENGINEERING\x10\x01\"(\n\x0bStudentList\x12\x19\n\x07student\x18\x01 \x03(\x0b\x32\x08.Studentb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STUDENT_DEPARTMENT = _descriptor.EnumDescriptor(
  name='Department',
  full_name='Student.Department',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMPUTER_SCIENCE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ELECTRICAL_ENGINEERING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=98,
  serialized_end=160,
)
_sym_db.RegisterEnumDescriptor(_STUDENT_DEPARTMENT)


_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Student.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='studentId', full_name='Student.studentId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dept', full_name='Student.dept', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STUDENT_DEPARTMENT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=160,
)


_STUDENTLIST = _descriptor.Descriptor(
  name='StudentList',
  full_name='StudentList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='student', full_name='StudentList.student', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=202,
)

_STUDENT.fields_by_name['dept'].enum_type = _STUDENT_DEPARTMENT
_STUDENT_DEPARTMENT.containing_type = _STUDENT
_STUDENTLIST.fields_by_name['student'].message_type = _STUDENT
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
DESCRIPTOR.message_types_by_name['StudentList'] = _STUDENTLIST

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), dict(
  DESCRIPTOR = _STUDENT,
  __module__ = 'students_pb2'
  # @@protoc_insertion_point(class_scope:Student)
  ))
_sym_db.RegisterMessage(Student)

StudentList = _reflection.GeneratedProtocolMessageType('StudentList', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTLIST,
  __module__ = 'students_pb2'
  # @@protoc_insertion_point(class_scope:StudentList)
  ))
_sym_db.RegisterMessage(StudentList)


# @@protoc_insertion_point(module_scope)
